displayName=AttackTimer
author=ngraves95,Lexer747
build=standard
description=A plugin to countdown until your next attack
tags=pvm,timer,attack,combat,weapon
plugins=com.attacktimer.AttackTimerMetronomePlugin